const termsOfService = {
  "ARTIKEL 1. DEFINITIES": [
    "1.1. TLW: de besloten vennootschap TLW, gevestigd te Almere en ingeschreven bij de Kamer van Koophandel onder nummer 80644279.",
    "1.2. Klant: de natuurlijke persoon of rechtspersoon die met TLW een overeenkomst is aangegaan en werkt vanuit zijn/haar beroep of bedrijf.",
    "1.3. Onder 'algemene voorwaarden' wordt verstaan: het geheel als bepalingen zoals die in dit document zijn opgenomen.",
    "1.4. Diensten/werkzaamheden: alle diensten/werkzaamheden die TLW voor de klant gaat uitvoeren. Hieronder worden onder andere verstaan maar niet uitsluitend: het als online marketing en business coach ondersteunen en begeleiden van ondernemers bij het opzetten van een consistente klantenstroom via online kanalen door middel van 1:1 coachingtrajecten, online trainingen, groepstrajecten, een DIY-academy, online masterclasses en losse online cursussen. Tevens het geven van coaching en cursussen over investeren met cryptocurrency en crypto-coaching i.c.m. business coaching en het geven van lezingen over crypto.",
    "1.5. Overeenkomst: de overeenkomst tussen TLW en de klant op basis waarvan TLW de diensten zal gaan uitvoeren.",
    "1.6. Informatie: alle gegevens die de klant aan TLW aanlevert.",
    "1.7. Schriftelijk: per brief, e-mail en digitale berichtgeving.",
    "1.8. Vertrouwelijke informatie: alle financiële-, zakelijke en persoonsgegevens die door de klant en/of TLW worden verstrekt, ingevoerd, opgeslagen en verwerkt.",
    "1.9. Website: www.tinekezwart.com."
  ],
  "ARTIKEL 2. TOEPASSELIJKHEID VAN DEZE ALGEMENE VOORWAARDEN": [
    "2.1. Deze algemene voorwaarden zijn van toepassing op alle door TLW gedane aanbiedingen, uitgebrachte oYertes, gesloten overeenkomsten, verrichte diensten, andere verrichte handelingen en facturen tenzij schriftelijk anders is overeengekomen.",
    "2.2. Door een akkoord via de e-mail, het accepteren van een online oYerte en/of een bestelling via de website te plaatsen, en expliciet akkoord te geven, verklaart de klant dat hij/zij kennis heeft genomen van deze algemene voorwaarden en akkoord gaat met de inhoud hiervan.",
    "2.3. Als er verschillen zijn tussen bepalingen uit deze algemene voorwaarden en bepalingen in een getekende overeenkomst, gaan de bepalingen uit de overeenkomst boven de bepalingen in deze algemene voorwaarden.",
    "2.4. Deze algemene voorwaarden zijn ook van toepassing op handelingen en/of werkzaamheden die door derden worden uitgevoerd die door TLW zijn ingehuurd voor het uitvoeren van werkzaamheden binnen deze overeenkomst.",
    "2.5. De toepasselijkheid van de algemene voorwaarden en/of inkoopvoorwaarden van de klant worden uitdrukkelijk van de hand gewezen. Andere voorwaarden zijn dus niet van toepassing op de gesloten overeenkomst.",
    "2.6. TLW mag de algemene voorwaarden altijd wijzigen, ook voor bestaande overeenkomsten.",
    "2.7. Als TLW de algemene voorwaarden wijzigt, zal TLW de klant hiervan zowel per e-mail als ook via een eventueel online account van de klant op de hoogte stellen.",
    "2.8. In geval van een wijziging van de algemene voorwaarden mag de klant de overeenkomst ontbinden vanaf het moment dat de nieuwe algemene voorwaarden geldig worden, of tot maximaal 7 dagen na het in werking treden van de nieuwe algemene voorwaarden.",
    "2.9. Indien een bepaling uit deze algemene voorwaarden ongeldig wordt verklaard zullen de overige bepalingen van deze algemene voorwaarden volledig van kracht blijven en zullen TLW en de klant in overleg een nieuwe bepaling opstellen om de ongeldig verklaarde bepaling te vervangen. Hierbij moet het doel en de strekking van de ongeldig verklaarde bepaling in het achterhoofd worden gehouden."
  ],
  "ARTIKEL 3. AANBOD": [
    "3.1. Als een aanbod van TLW een beperkte geldigheidsduur heeft, wordt dit duidelijk in het aanbod aangegeven. Als er geen termijn is aangegeven, is het aanbod geldig tot 14 dagen na de datum waarop het aanbod is uitgebracht. Als de klant het aanbod niet binnen die 14 dagen accepteert, vervalt het aanbod. Het aanbod is daarnaast onder voorbehoud van beschikbaarheid en een eventuele startdatum van een (groeps)programma.",
    "3.2. Zolang de klant het aanbod niet binnen de genoemde termijn heeft geaccepteerd, mag TLW het aanbod en de bijbehorende tarieven intrekken of wijzigen.",
    "3.3. TLW geeft in het aanbod aan welke dienst of welk programma wordt aangeboden, het overeengekomen tarief.",
    "3.4. Als blijkt dat de klant bij de aanvraag onjuiste en/of onvolledige gegevens heeft doorgegeven, mag TLW de tarieven en aanvullende voorwaarden aanpassen.",
    "3.5. Het aanbod en/of de speciale actie geldt niet automatisch voor vervolgopdrachten.",
    "3.6. Het aanbod bevat een volledige omschrijving van de aangeboden diensten, de beschrijving is voldoende gedetailleerd om een goede beoordeling van het aanbod door de klant mogelijk te maken.",
    "3.7. TLW mag een volledige vooruitbetaling, een aanbetaling van 50% of een aanbetaling ter waarde van de eerste termijn van het overeengekomen tarief aan de klant in rekening brengen. De uitvoering van de diensten, zoals het laten plaatsvinden van een kick-oY, zullen pas starten nadat de betaling is voldaan. Tenzij anders overeengekomen, wordt het restantbedrag in meerdere, gelijke termijn aan de klant gefactureerd.",
    "3.8. TLW mag de tarieven tussentijds wijzigen. Als de tarieven van overeengekomen diensten stijgen na het sluiten van de overeenkomst, dan mag de klant de overeenkomst annuleren per de datum dat de prijsverhoging ingaat. Prijsverhogingen door wettelijke regelingen of bepalingen zijn hierbij uitgesloten.",
    "3.9. Alles wat buiten het aanbod aan de klant wordt geleverd, wordt als meerwerk gezien en als zodanig in rekening gebracht.",
    "3.10. TLW kan niet aan het aanbod worden gehouden als de klant redelijkerwijs kon begrijpen dat het aanbod, of een onderdeel daarvan, en kennelijke vergissing, verschrijving of typefout bevat."
  ],
  "ARTIKEL 4. OVEREENKOMST, MEERWERK, ONTBINDEN, ANNULEREN EN WIJZIGEN": [
    "4.1. De overeenkomst komt tot stand vanaf het moment dat de klant het akkoord op het aanbod via de e-mail aan TLW stuurt, de oYerte online accepteert of zich via de website inschrijft door middel van een bestelling voor een online dienst. Wijzigingen in gesloten overeenkomsten kunnen alleen schriftelijk worden gedaan en zijn pas geldig wanneer deze door TLW en de klant zijn geaccepteerd.",
    "4.2. Na het sluiten van de overeenkomst zal TLW binnen de afgesproken termijn starten met de levering van de diensten. Als de klant het aanbod elektronisch heeft geaccepteerd, bevestigt TLW de acceptatie van het aanbod. Zolang TLW de acceptatie niet heeft bevestigd, mag de klant de overeenkomst kosteloos ontbinden.",
    "4.3. TLW mag bepaalde werkzaamheden uit laten voeren door derden of zich laten ondersteunen zonder dat de klant daarvan vooraf op de hoogte gesteld moet te worden.",
    "4.4. Als TLW door onvoorziene omstandigheden, die op het moment van het opstellen van het aanbod nog niet bekend waren, meer werk moet uitvoeren dan is overeengekomen in het aanbod, mag TLW de daaruit voortkomende meerkosten als meerwerk aan de klant in rekening te brengen.",
    "4.5. Ingeval van annulering voor of bij aanvang, gedeeltelijke deelname of tussentijdse beëindiging van een online traject door de klant, vanwege andere redenen dan overmacht of nalatigheid van TLW, behoudt TLW het recht op het volledige overeengekomen tarief voor de betreYende overeengekomen diensten. De betalingsverplichting voor de klant komt niet te vervallen en indien er al betalingen hebben plaatsgevonden, vindt er geen restitutie plaats.",
    "4.6. Wanneer de klant een overeenkomst, betreYende een 1:1 coachingtraject of lezing en dus niet zijnde een online traject zoals genoemd in artikel 4.5, voor aanvang van de start van het traject of de lezing wil annuleren, is dit alleen schriftelijk mogelijk en is de klant verplicht om een vergoeding voor de gereserveerde tijd te betalen: • annulering tot 14 dagen voor aanvang: 10% van het in het aanbod overeengekomen bedrag; • annulering binnen 14 dagen voor aanvang: 25% van het in het aanbod overeengekomen bedrag.",
    "4.7. Het door de klant geaccepteerde aanbod, eventueel gesloten overeenkomst en deze algemene voorwaarden vormen samen de volledige weergave van de rechten en verplichtingen van beide partijen en vervangen alle eerdere schriftelijke en mondelinge afspraken.",
    "4.8. Indien zich wijzigingen voordoen met betrekking tot de omstandigheden waarop TLW zich heeft gebaseerd bij het uitbrengen van het aanbod, dan is TLW bevoegd deze wijzigingen te wijzigen in de uitvoering van de overeenkomst dan wel de prijzen aan te passen."
  ],
  "ARTIKEL 5. UITVOERING VAN DE OVEREENKOMST": [
    "5.1. Iedere overeenkomst tussen TLW en de klant is een inspanningsverplichting waarbij TLW de verplichtingen naar beste vermogen en inzicht zal uitvoeren, met de nodige zorgvuldigheid en vakmanschap. TLW kan echter niet verantwoordelijk worden gehouden als het resultaat niet aan de verwachtingen van de klant voldoet.",
    "5.2. TLW zorgt ervoor dat (vertrouwelijke) informatie die de klant aan TLW levert zodanig wordt beveiligd dat deze gegevens niet beschikbaar zijn voor onbevoegde personen.",
    "5.3. TLW is bevoegd om voor promotionele doeleinden, voor bijvoorbeeld referenties, de gegevens van de klant op de website en/of social media kanalen te publiceren.",
    "5.4. De klant is verplicht om alle informatie die nodig zijn voor de uitvoering van de werkzaamheden, zoals persoons- en bedrijfsgegevens en informatie over of met betrekking tot de uit te voeren werkzaamheden en relevante informatie waar TLW om verzoekt, uiterlijk 48 uur voor aanvang van de kick-oY aan TLW beschikbaar te stellen. De klant is verantwoordelijk voor de juistheid, volledigheid en betrouwbaarheid van deze gegevens, ook als ze van derden afkomstig zijn.",
    "5.5. Als de klant de gegevens uit artikel 5.4 niet of niettijdig aan TLW beschikbaar stelt en de uitvoering van de diensten daardoor vertraging oploopt, dan komen de daaruit voortvloeiende extra kosten voor rekening van de klant. Daarnaast mag TLW eenzijdig besluiten om de uitvoering van de diensten op te schorten tot het moment dat de gegevens door TLW zijn ontvangen.",
    "5.6. Als door toedoen van TLW de uitvoering van de diensten vertraging oploopt door ziekte of vanwege andere onvoorziene (persoonlijke) omstandigheden, zal TLW dit zo snel mogelijk aan de klant meedelen.",
    "5.7. In geval van een traject en/of programma met een vooraf bepaalde duur is de klant is zelf verantwoordelijk voor het tijdig inplannen van afspraken en/of coachingsessies. Niet tijdig ingeplande afspraken en/of sessies en eventuele ingestuurde opdrachten komen te vervallen na afloop van de duur van de overeenkomst. Tevens kan door de klant geen aanspraak meer gemaakt worden op niet of nog niet genoten onderdelen van de opdracht in welke vorm dan ook.",
    "5.8. In uitzondering op artikel 5.7. kan, tenzij anders overeengekomen, het traject enkel met maximaal 4 weken worden verlengd indien de klant ziek is of met vakantie is geweest.",
    "5.9. De klant wordt in de gelegenheid gesteld vragen te stellen via WhatsApp, TLW zal op werkdagen (maandag t/m donderdag) tussen 9-17 uur deze vragen binnen 24 uur, met uitzondering van de vakanties van TLW, het weekend en feestdagen, beantwoorden. Vakanties van TLW worden tijdig aan de klant gemeld. Tijdens de gemelde vakantie is TLW niet bereikbaar.",
    "5.10. In aanvulling op artikel 5.9 mag de klant ook vragen per e-mail aan TLW sturen. Deze e-mails worden binnen 2 werkdagen beantwoord."
  ],
  "ARTIKEL 6. RECHTEN EN VERPLICHTINGEN VOOR DE KLANT": [
    "6.1. De klant moet zich houden aan de bepalingen zoals deze zijn opgenomen in deze algemene voorwaarden.",
    "6.2. De klant is verplicht om wijzigingen in de gegevens zoals genoemd in artikel 5.4. zo spoedig mogelijk aan TLW te melden.",
    "6.3. De klant is verplicht om klachten over de door TLW geleverde diensten en/of digitale producten zo snel mogelijk, uiterlijk binnen 7 dagen na een coachingsessie en uiterlijk binnen 30 dagen na afronding van het traject of programma, aan TLW te melden. TLW streeft ernaar binnen 5 werkdagen op de klacht te reageren.",
    "6.4. De klant is verplicht TLW een redelijk termijn te geven om de klacht en/of het geconstateerde gebrek te herstellen. Het indienen van een klacht schort de betalingsverplichting niet op.",
    "6.5. Eén jaar na levering van de producten en/of diensten vrijwaart de klant TLW van alle juridische claims naar aanleiding van die geleverde diensten en/of producten.",
    "6.6. De klant moet zelf reservekopieën maken van alle materialen en/of gegevens die TLW nodig heeft voor de uitvoering van de diensten. Bij verlies van deze materialen en/of gegevens is TLW niet aansprakelijk voor de schade die daaruit voortkomt.",
    "6.7. Als TLW inloggegevens met de klant deelt, dan is de klant verantwoordelijk voor deze gegevens. TLW is niet aansprakelijk voor misbruik en/of verlies van de inloggegevens en mag ervan uitgaan dat de klant degene is die inlogt door middel van de met de klant gedeelde inloggegevens.",
    "6.8. Er bestaat geen herroepingsrecht, nu de klant altijd een zakelijke opdrachtgever is.",
    "6.9. In aanvulling op artikel 6.8 is het niet mogelijk aangeschafte digitale producten, waaronder een een online dienst zoals een online cursus, online traject, programma, template, DIY training of betaald e-book, te retourneren. Door bestelling en betaling van de digitale producten krijgt klant direct de volledige toegang tot de aankoop."
  ],
  "ARTIKEL 7. BIJZONDERE BEPALINGEN (1:1) COACHINGSTRAJECT, (GROEPS)PROGRAMMA'S, CRYPTOCOACHING EN CRYPTO-CURSUSSEN": [
    "7.1. Zodra de klant het aanbod van TLW heeft geaccepteerd, ontstaat er een betalingsverplichting voor de klant, ook wanneer niet het hele traject of het hele programma wordt gevolgd.",
    "7.2. De kennis die door de klant wordt opgedaan, mag niet worden gekopieerd en mag alleen voor eigen doeleinden gebruikt worden.",
    "7.3. In aanvulling op artikel 7.2 is het de klant niet toegestaan, ongeacht (volledige) deelname of niet, om binnen 30 dagen na afronding van het traject en/of het programma een soortgelijk traject/programma al dan niet met referentie naar of volgens de methode van TLW aan te bieden of te doen geven. Als TLW waarneemt dat de klant de content geheel of gedeeltelijk heeft gekopieerd, is het aan de klant om aan te tonen dat dit niet het geval is, en is artikel 9 van toepassing.",
    "7.4. De klant erkent dat eventueel resultaat niet direct zicht- en meetbaar zal zijn en dat eventuele resultaten afhankelijk zijn van de inzet van de klant zelf en de manier waarop de klant de opdrachten uitvoert en resultaten binnen het bedrijf implementeert. TLW geeft geen enkele garanties voor het behalen van een bepaald resultaat door de klant.",
    "7.5. TLW geeft in het aanbod aan hoe lang de content binnen de online leeromgeving beschikbaar blijft nadat het traject/het programma is afgelopen. Indien TLW toch besluit materiaal (eerder) te verwijderen of te verhuizen, stelt TLW de klant hier drie maanden voorafgaand aan de verhuizing of verwijdering van op de hoogte, via het meest recente bekende e-mailadres van de klant. De klant is zelf verantwoordelijk voor het tijdig volgen van de content en eventueel downloaden van bestanden.",
    "7.6. Indien de klant langer toegang wil houden tot de content, kan de klant bij TLW een verzoek indienen voor eventuele verlenging van de toegang tot de content.",
    "7.7. Inloggegevens met betrekking tot de online leeromgeving en andere online content mogen niet met derden worden gedeeld. Indien TLW waarneemt dat door toedoen van de klant derden toegang hebben tot de online leeromgeving en/of afgeschermde content van TLW, is TLW gerechtigd de toegang voor de klant, zonder voorafgaande waarschuwing, te ontzeggen.",
    "7.8. TLW maakt gebruik van software van een derde partij (leverancier) om de content binnen de online leeromgeving digitaal aan de klant beschikbaar te stellen. TLW kan niet garanderen dat die software altijd en overal te bereiken is en aanvaard geen aansprakelijkheid voor het tijdelijk niet bereikbaar zijn van de content.",
    "7.9. TLW mag het aanbod en de bijbehorende content binnen een traject/programma uitbreiden, beperken of aanpassen in verband met kwalitatieve verbeteringen zodra TLW dit nodig acht.",
    "7.10. TLW beheert een online community. Wanneer de klant dit wil kan de klant lid worden van deze online community door toegang tot deze groep te vragen. Alleen klanten met een actief coachingtraject zijn gerechtigd om aan deze groep deel te nemen. De online community wordt aangeboden als extra dienstverlening, de klant kan hier geen enkele rechten aan ontlenen en het staat TLW vrij deze online community te beëindigen.",
    "7.11. De klant kan in de online community van TLW berichten plaatsen. De klant is te allen tijde verantwoordelijk voor de inhoud van de berichten die worden geplaatst. Berichten mogen geen reclame, ongevraagde acquisitie, spam, discriminerende, pornografische, beledigende of bedreigende inhoud bevatten of op andere manier wijze de wet overtreden en andere deelnemers schaden. TLW mag deze informatie altijd zonder opgaaf van redenen verwijderen.",
    "7.12. Als de klant de sfeer binnen de training, het traject of de community verstoort door haar gedrag, of berichten plaatst in de community welke in strijd zijn met artikel 7.11, dan mag TLW de klant de toegang ontzeggen en toekomstige deelname weigeren. Dit heeft geen enkele invloed op door de klant betaalde gelden of betalingsverplichtingen van de klant.",
    "7.13. De klant is niet gerechtigd screenshots en/of geluidsopnames te maken van de online trainingen, online leeromgeving en/of masterclasses.",
    "7.14. Deelname van de klant aan een online groepsactiviteit kan niet worden verplaatst of ingehaald in geval van afwezigheid. TLW maakt een planning voor de groepsactiviteiten en stelt de klant daarvan tijdig op de hoogte. Indien mogelijk kan TLW de content en/of opname van een groepssessie delen met de klant. Het niet (kunnen) deelnemen leidt niet tot restitutie van betaalde gelden of opschorting van een betalingsverplichting.",
    "7.15. Indien TLW door overmacht (genoemd in artikel 12) genoodzaakt is om een online groepsactiviteit, welke onderdeel is van een traject, te verplaatsen, behoudt de klant het recht op aanwezigheid voor activiteit voor de nader te bepalen datum.",
    "7.16. TLW mag, wanneer de klant in termijnen betaalt en de termijnbetaling(en) niet-tijdig heeft gedaan, het recht op deelname aan het traject/hetpgrogramma en toegang tot de online leeromgeving blokkeren (opschorten) tot er een betaling heeft plaatsgevonden. Indien de toegang tot een online leeromgeving is ontzegt, zal de klant weer toegang krijgen zodra de betalingsachterstand is ingelopen.",
    "7.17. TLW geeft de klant de mogelijkheid, om binnen het traject of het programma met een vooraf bepaalde duur, een ingeplande coachingsessie één keer te verplaatsen, mits dit 24 uur voor aanvang van de sessie aan TLW wordt gemeld. Indien de klant dit niet uiterlijk 24 uur voor aanvang van de sessie aan TLW meldt, de klant zonder afmelding niet aanwezig is voor de sessie, meer dan 15 minuten te laat is voor de sessie of dezelfde sessie voor een tweede keer wenst te verplaatsen, komt de sessie te vervallen. Vervallen of gemiste sessies kunnen niet worden ingehaald.",
    "7.18. Indien TLW is verhinderd voor een overeengekomen (1:1) sessie binnen het traject en/of het programma, zal in overleg met de klant de sessie worden verplaatst.",
    "7.19. Casuïstiek die binnen een traject en/of programma wordt behandeld en/of besproken kan worden gebruikt in blogs en in (praktijk)voorbeelden op social media. Deze verhalen en/of voorbeelden worden volledig anoniem en onherkenbaar/naar een persoon herleidbaar ingezet."
  ],
  "CRYPTO-COACHING EN CRYPTO-CURSUSSEN": [
    "7.20. Alle handelingen die de klant uitvoert na het volgen van de cursus en/of coaching betreYende beleggen en investeren met cryptocurrency, zijn en blijven voor eigen risico van de klant. TLW geeft enkel algemene informatie, dit wil zeggen dat er géén rekening gehouden wordt met de persoonlijke situatie en/of de financiële situatie van de klant. TLW is géén financieel adviseur, geeft uitdrukkelijk géén financieel advies en is daardoor nooit aansprakelijk voor de gevolgen van de handelingen die de klant zelf uitvoert.",
    "7.21. De klant dient er te allen tijde rekening mee te houden dat handelen in cryptocurrency en het investeren van geld verschillende risico's met zich meebrengt. Daaronder valt ook het risico om de volledige investering te verliezen.",
    "7.22. TLW biedt algemene informatie en educatie over beleggen, investeren en cryptocurrency maar biedt uitdrukkelijk géén persoonlijk en/of financieel advies. Het is mogelijk dat de verstrekte informatie en de educatie niet geschikt is voor de (individuele) behoefte, doelstellingen of financiële situatie van de klant.",
    "7.23. De klant dient, voordat de klant aan de slag gaat met de verstrekte informatie, zelf af te wegen of handelen in cryptocurrency past bij de eigen financiele situatie en risicobereidheid. TLW adviseert de klant te allen tijde om professioneel en financieel advies in te winnen om te bepalen of investeren in een financieel product geschikt is bij de omstandigheden van de klant voordat de klant investeringsbeslissingen neemt.",
    "7.24. De informatie en/of de educatie kan aanbevelingen bevatten met betrekking tot de omvang van de investering, in- en uitstapmomenten, risico's, strategieën, adviezen over te gebruiken systemen, welke currency gebruikt kan worden en mindset-coaching.",
    "7.25. Eventuele eerdere resultaten, inkomsten en percentages bieden geen garanties voor de toekomst en/of voor de klant. Eventuele afbeeldingen, illustraties, portfolio's en voorbeelden zijn uitsluitend ter illustratie. De klant begrijpt dat financiële instrumenten in waarde kunnen stijgen en/of dalen en resultaten die TLW toont wellicht niet overeenkomen met de resultaten van de klant."
  ],
  "ARTIKEL 8. BETALING": [
    "8.1. Zodra het aanbod door de klant is geaccepteerd, is ook de verplichting ontstaan tot betaling van het overeengekomen tarief.",
    "8.2. Facturen dienen binnen 14 kalenderdagen na de factuurdatum betaald te zijn, behalve als er andere afspraken zijn gemaakt of op de factuur een andere betaaltermijn vermeld is.",
    "8.3. De eerste termijnbetaling of de aanbetalingsfactuur dient te zijn voldaan voor aanvang van de kick-oY sessie.",
    "8.4. TLW biedt de klant de mogelijkheid om in vooraf overeengekomen termijnen te betalen. Indien de termijn betaling(en) niet-tijdig worden voldaan, is TLW bevoegd de werkzaamheden uit te stellen tot een volgende betaling is gedaan.",
    "8.5. Indien niet-tijdige betaling drie keer is voorgekomen, kan TLW besluiten de opdracht eenzijdig te beëindigen en/of de mogelijkheid tot termijnbetalingen op te heYen en is het resterende bedrag direct en in zijn totaliteit opeisbaar door TLW.",
    "8.6. Als de klant niet-tijdig aan de betalingsverplichting voldoet, is de klant van rechtswege in verzuim zonder dat een verdere ingebrekestelling nodig is.",
    "8.7. Bij een niet tijdige betaling is de klant, naast het verschuldigde bedrag vermeerderd met de wettelijke (handels)rente, verplicht tot een volledige vergoeding van zowel buitengerechtelijke als gerechtelijke incassokosten welke ten minste 15% van het factuurbedrag met een minimum van €150,- excl. BTW bedragen.",
    "8.8. In geval van liquidatie, faillissement, beslag, surseance van betaling of overlijden aan de zijde van de klant zijn de vorderingen van TLW onmiddellijk opeisbaar.",
    "8.9. In aanvulling op artikel 8.8 heeft TLW het recht de uitvoering van de werkzaamheden of het nog niet uitgevoerde gedeelte daarvan, zonder ingebrekestelling of rechterlijke interventie te beëindigen of op te schorten, zonder recht op vergoeding van schade voor de klant die hierdoor mocht ontstaan.",
    "8.10. De klant kan bezwaren tegen de door TLW verzonden facturen uiterlijk binnen vijf dagen na factuurdatum schriftelijk aan TLW kenbaar maken. Na ontvangst van het bezwaar zal TLW een onderzoek instellen naar de juistheid van het factuurbedrag. Bezwaren tegen verzonden facturen schorten de betalingsverplichting van de klant niet op."
  ],
  "ARTIKEL 9. INTELLECTUEEL EIGENDOM": [
    "9.1. Alle intellectuele eigendomsrechten op alle geleverde diensten, producten, documentatie en/of materialen berusten bij TLW tenzij anders is overeengekomen. Het is de klant in geen enkel geval toegestaan de geleverde diensten, producten, documentatie en/of materialen, te veelvoudigen, door te verkopen, openbaar te maken en/of aan derden ter beschikking te stellen, behalve als schriftelijk anders is overeengekomen.",
    "9.2. De intellectuele eigendomsrechten op door TLW ontwikkelde voortbrengselen van de menselijke geest, zijn en blijven exclusief eigendom van TLW tenzij de rechten worden afgekocht of anders is overeengekomen.",
    "9.3. TLW is niet verantwoordelijk voor de informatie en/of content die via de klant met TLW wordt gedeeld of ter beschikking is gesteld. Indien de door de klant aangeleverde informatie en/of content op een manier inbreuk maakt op rechten van derden en/of in strijd is met de geldende wet- en regelgeving, zal de klant TLW vrijwaren van enige aanspraken op schadevergoeding die derden eisen als gevolg van dit handelen van de klant.",
    "9.4. Iedere handeling die in strijd is met dit artikel wordt gezien als inbreuk op het auteursrecht waarbij TLW recht heeft op een vergoeding ter hoogte van minimaal tweemaal de door TLW gehanteerde licentievergoeding voor een dergelijke vorm van gebruik zonder het recht op enige schadevergoeding te verliezen"
  ],
  "ARTIKEL 10. DUUR OVEREENKOMST EN BEËINDIGING": [
    "10.1. De overeenkomst wordt aangegaan voor bepaalde tijd, behalve als uit het aanbod anders voortvloeit of als partijen uitdrukkelijk en schriftelijk andere afspraken hebben gemaakt.",
    "10.2. De klant kan de overeenkomst niet tussentijds opzeggen.",
    "10.3. Beide partijen mogen de overeenkomst alleen ontbinden als de andere partij na een deugdelijke schriftelijke ingebrekestelling niet aan de verplichtingen voldoet. In ieder geval moet er een redelijke termijn zijn gesteld om de tekortkoming te herstellen.",
    "10.4. In uitzondering op artikel 10.3. kan TLW de overeenkomst zonder ingebrekestelling en zonder rechterlijke tussenkomst door schriftelijke kennisgeving direct geheel of gedeeltelijk beëindigen als zich een dringende reden voordoet waaronder in ieder geval wordt begrepen dat: • surseance van betaling aan de klant is verleend; • het faillissement van de klant is uitgesproken; • het vermoeden bestaat dat de klant niet aan de betalingsverplichting kan (blijven) voldoen en/of terugkerende betalingsproblemen; • de klant handelt in strijd met de openbare orde, goede zeden en/of wet- en regelgeving; • de klant inbreuk maakt op rechten van derden; • de klant handelt in strijd met een verplichting die voortkomt uit de overeenkomst; • de klant niet reageert op correspondentie per e-mail, telefoon en/of schriftelijk al dan niet per aangetekend schrijven en redelijke richtlijnen en/of aanwijzingen van TLW negeert; • er voor TLW aanwijzingen en/of (nieuwe) feiten en omstandigheden zijn dat TLW zich niet (meer) naar beste kunnen kan inzetten, bijvoorbeeld vanwege een vertrouwensbreuk met de klant, om de werkzaamheden uit te voeren.",
    "10.5. TLW zal, indien de overeenkomst wordt beëindigd vanwege een situatie uit artikel 10.4 het resterende bedrag voor de werkzaamheden aan de klant retourneren maar nooit verplicht zijn om een schadevergoeding aan de klant te betalen.",
    "10.6. Als TLW op het moment van de beëindiging zoals genoemd in dit artikel al betalingen met betrekking tot de werkzaamheden heeft ontvangen, zullen deze betalingen niet met terugwerkende kracht worden terugbetaald. Daarnaast blijven bedragen die TLW vóór de ontbinding aan de klant heeft gefactureerd nog steeds verschuldigd en worden op het moment van de ontbinding direct opeisbaar."
  ],
  "ARTIKEL 11. AANSPRAKELIJKHEID": [
    "11.1. De klant is en blijft altijd zelf verantwoordelijk voor het uitvoeren of toepassen van kennis, handelingen en/of adviezen die door TLW tijdens het uitvoeren van de werkzaamheden worden gegeven. TLW heeft enkel een adviserende rol.",
    "11.2. Indien TLW toch, ondanks artikel 11.1, toch aansprakelijk wordt gesteld, is iedere aansprakelijkheid beperkt tot vergoeding van directe schade tot maximaal tweemaal van het overeengekomen tarief voor de betreYende werkzaamheden. Als er sprake is van een duurovereenkomst of betaling in termijnen, is de aansprakelijkheid beperkt tot vergoeding van de directe schade tot maximaal het bedrag van de door de klant laatst betaalde factuur.",
    "11.3. De klant heeft pas recht op een schadevergoeding als de klant TLW heeft gewezen op de toerekenbare tekortkoming en/of onrechtmatige gedraging tegenover de klant door middel van een ingebrekestelling. In de ingebrekestelling dient de klant TLW een redelijk termijn te geven om de tekortkoming te herstellen en/of alsnog na te komen. Alleen wanneer TLW niet heeft voldaan aan herstel en/of nakoming, heeft de klant mogelijk recht op een schadevergoeding. Als de nakoming en/of het herstel blijvend onmogelijk is, geld het vereiste van een ingebrekestelling niet.",
    "11.4. In aanvulling op artikel 11.2 is TLW alleen aansprakelijk voor directe schade zoals de redelijke kosten ter vaststelling van de oorzaak en de omvang van de schade, eventuele redelijke kosten die de klant moet maken om de schade te laten herstellen en redelijke kosten die gemaakt dienen te worden ter voorkoming of beperking van de schade voor zover de klant kan aantonen dat deze kosten hebben geleid tot beperking van directe schade als bedoeld in dit artikel.",
    "11.5. TLW is niet aansprakelijk voor schade die voortvloeit uit deze overeenkomst, met uitzondering van situaties waarin de schade te wijten is aan opzet of grove schuld aan de kant van TLW",
    "11.6. TLW is in ieder geval nooit aansprakelijk voor indirecte of gevolgschade zoals gemiste besparingen, misgelopen winst, kosten voor juridische bijstand, verlies van klanten, herstelkosten, schade door bedrijfsstagnatie, voor schade ontstaan door verlies van de gegevens uit artikel 5.4 bij het uitvoeren van de werkzaamheden of voor schade wanneer TLW is uitgegaan van door of namens de klant verstrekte onjuiste of onvolledige gegevens.",
    "11.7. De klant vrijwaart TLW tegen alle aanspraken van derden, kosten daarbij inbegrepen, die op welke manier dan ook samenhangen met werkzaamheden die TLW in het kader van de overeenkomst heeft verricht.",
    "11.8. Er is door de klant geen enkel recht of verplichting te ontlenen aan het traject en/of het programma en ieder handelen van de klant is voor eigen rekening en risico. TLW aanvaardt geen enkele aansprakelijkheid voor de wijze waarop de klant de gedoceerde wijze en methode van TLW in de praktijk tot uitvoering brengt."
  ],
  "ARTIKEL 12. ONDERBREKING VAN DE WERKZAAMHEDEN EN OVERMACHT": [
    "12.1. TLW is niet gehouden aan de verplichting tot het uitvoeren van de werkzaamheden als de nakoming ervan onmogelijk is geworden door overmacht. Onder overmacht wordt een situatie verstaan waarin partijen redelijkerwijs geen invloed op uit kunnen oefenen zoals ziekte, een pandemie, ongevallen, brand, bedrijfsstoringen en overheidsmaatregelen.",
    "12.2. Indien zich een situatie zoals genoemd in artikel 12.1 voordoet, of andere omstandigheden plaatsvinden waardoor de werkzaamheden tijdelijk niet uitgevoerd kunnen worden, worden de verplichtingen opgeschort zolang partijen niet aan hun verplichtingen kunnen voldoen. Partijen zoeken in een dergelijke situatie samen naar een oplossing. Indien de overmacht meer dan 90 dagen heeft geduurd, zijn beide partijen bevoegd de overeenkomst schriftelijk te ontbinden. De tot dan toe gemaakte kosten en gewerkte uren worden onmiddellijk opeisbaar.",
    "12.3. TLW is bij het uitvoeren van de werkzaamheden in sommige gevallen afhankelijk van de medewerking, diensten en leveranties van derden waar TLW geen invloed op kan uitoefenen. TLW kan daarom niet aansprakelijk gesteld worden voor schade in geval van een situatie waarbij de schade te wijten is aan een derde partij waarmee TLW een overeenkomst is aangegaan.",
    "12.4. In geval van een zakelijke overeenkomst zijn partijen gehouden de werkzaamheden te verplaatsen en blijft de betalingsverplichting in stand."
  ],
  "ARTIKEL 13. OVERIGE BEPALINGEN EN TOEPASSELIJK RECHT": [
    "13.1. Als de klant in de opdracht bepalingen en/of voorwaarden opneemt die afwijken van, of niet voorkomen in, deze voorwaarden, dan zijn deze bepalingen en/of voorwaarden alleen bindend als TLW deze bepalingen en/of voorwaarden uitdrukkelijk schriftelijk heeft geaccepteerd.",
    "13.2. TLW spant zich in om passende technische en organisatorische maatregelen te treYen om de (persoons-)gegevens te beveiligen tegen verlies en/of tegen enige vorm van onrechtmatig gebruik door derden. Zie hiervoor ook de privacyverklaring.",
    "13.3. Partijen zijn verplicht tot geheimhouding van alle vertrouwelijke informatie die zij met betrekking tot de overeenkomst en de werkzaamheden hebben verkregen. Informatie is vertrouwelijk als dit door de andere partij wordt aangegeven of als dat blijkt uit redelijkheid en billijkheid.",
    "13.4. Indien TLW in het voordeel van de klant afwijkt van de algemene voorwaarden, kan de klant daar geen rechten aan ontlenen.",
    "13.5. Rechten en plichten die ontstaan uit de overeenkomst kunnen alleen van de klant op een andere partij worden overgedragen als TLW daar schriftelijk toestemming voor heeft gegeven.",
    "13.6. Op alle overeenkomsten en deze algemene voorwaarden is Nederlands recht van toepassing.",
    "13.7. Partijen zullen eventuele conflicten eerst samen proberen op te lossen voordat zij een beroep zullen doen op de rechter.",
    "13.8. Alle conflicten zullen worden beslecht door de bevoegde rechter in het arrondissement waarin TLW is gevestigd, behalve als een wettelijke verplichting anders bepaalt."
  ]
};

export default termsOfService;
